### ISSUE TITLE
The `timestamp` of type `date` in kibana needs to use format `epoch_second` if the value is in seconds

### ISSUE THREAD

**Issue by jsolman** [ElrondNetwork/elastic-indexer-go#25]
It seems the ElasticSearch date types need to use `epoch_second` for the format or they will default to `epoch_millis`. Since the timestamp is actually being written in seconds, this means kibana will not handle the time stamp properly.

This occurs in the `noKibana` and `Kibana` templates.

Example problem locations:

https://github.com/ElrondNetwork/elastic-indexer-go/blob/1ac01467646bca69b2945143106f687a67410c35/templates/noKibana/accountsHistory.go#L14-L16

https://github.com/ElrondNetwork/elastic-indexer-go/blob/1ac01467646bca69b2945143106f687a67410c35/templates/withKibana/transactions.go#L26-L28

What it should be instead:

```
			"timestamp": Object{
				"type": "date",
				"format": "epoch_second",
			},
```

Creating an issue instead of a PR, since I don't have time for the PR at the moment.
Looks like the problem also exists on the feat/new-indexer branch.

**Comment by miiu96** [comment]
Thank you for reporting this. I will make a PR with fixes. In all the indexes where we use `timestamp` as type `date`

**Comment by miiu96** [comment]
Opened a PR with the fixes https://github.com/ElrondNetwork/elastic-indexer-go/pull/26
